### ISSUE TITLE
Spike: Test Updating Server .NET Core Framework to 3.1

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/dotnet-api-template#6]
## In order to continue supporting our apps the .NET Core framework on servers needs to be update to 3.1 before 8/21/2021.

*Examples:*
* The hope is that we can just update the server framework and it supports backwards compatibility for 2.1.

> **Estimation** *#* 

### Expected Deliverables:
* Can we do the update without having to change code for any of our apps

**Comment by blairlearn** [comment]
The quick answer is, there isn't a quick shortcut.
* You cannot run .Net 2.1 code on the 3.1 runtime.
* There are breaking changes that stop a straight recompile from working.
* I finally ended up taking the clinical trial listing API and making the code changes to go from 2.1 -> 2.2 -> 3.0 -> 3.1

Issue 1959 in the https://github.com/dotnet/runtime/ repository talks about this.  The short version is, this is a deliberate breaking change and requires modifying some code.  (**Note:** Deliberately not linking to the issue in order to keep our issue from showing up in their history.)
